### ISSUE TITLE
Using Secure Base url

### ISSUE THREAD

**Issue by abdulwahabone** [maxzod/alquran_cloud#1]
Getting DioError Insecure HTTP is not allowed by platform: http://api.alquran.cloud/v1/.......

Is there any way we can allow baseUrl for quranCloud to be https instead of http ?

**Comment by maxzod** [comment]
i will look into this today  👍

**Comment by abdulwahabone** [comment]
Thank you brother.

**Comment by maxzod** [comment]
until i push this update to `pub.dev` you can use the package from this repo directly  in your `pubspec.yaml`
use this code 

```yaml
dependencies:
  alquran_cloud:
    git:
      url: git@github.com:maxzod/alquran_cloud.git
      ref: 7241c69f6c06c8a58a70d44ee1abc5e917e34d6e
```
